eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8791/eureka
    
  instance:
    hostname: localhost
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        url: http://PAYMENT-SERVICE/payment/doPayment
        
  order-service:
    endpoints:
      endpoint:
        url: http://ORDER-SERVICE/order/bookOrder
    
